### ISSUE TITLE
Migrate this connector to our konnectors team

### ISSUE THREAD

**Issue by drazik** [carrieje/cozy-konnector-nef#1]
Hello @carrieje. First of all, thank you for this connector ! I'm working for Cozy and we would like to test and improve it. I have a question : would you be OK to migrate it to our [konnectors](https://github.com/konnectors) team so we can both take care of it easily ?

Thanks.

**Comment by carrieje** [comment]
Yes of course!
Go ahead ;-)

**Comment by carrieje** [comment]
I haven't tried it with an account that had many operations.
https://github.com/carrieje/cozy-konnector-nef/blob/master/index.js#L119
For instance this parameter seems to tell there is pagination on the operations display screen.

But for my account and my operations, it works fine.

**Comment by drazik** [comment]
Thank you very much ! It is now located here : https://github.com/konnectors/cozy-konnector-nef
Of course you still have the rights to continue to maintain it, even if it is under our Konnectors team :)
